# loading Libraries

In [156]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.experimental import enable_iterative_imputer # مطلوب لتفعيل الخوارزمية
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer
from sklearn.preprocessing import OrdinalEncoder, MinMaxScaler
from sklearn.ensemble import RandomForestRegressor
import warnings
warnings.filterwarnings('ignore')

# loading Datasets

In [157]:
Dim_Customers = pd.read_csv("D:\mohanad study\ERU Study\level 3\semester 2\Predictive Analytics\project\GoldExports\Gold_Dim_Customers_2026-05-08.csv")
Dim_Date = pd.read_csv("D:\mohanad study\ERU Study\level 3\semester 2\Predictive Analytics\project\GoldExports\Gold_Dim_Date_2026-05-08.csv")
Dim_Products = pd.read_csv("D:\mohanad study\ERU Study\level 3\semester 2\Predictive Analytics\project\GoldExports\Gold_Dim_Products_2026-05-08.csv")
Dim_Sellers = pd.read_csv("D:\mohanad study\ERU Study\level 3\semester 2\Predictive Analytics\project\GoldExports\Gold_Dim_Sellers_2026-05-08.csv")
Fact_Orders = pd.read_csv("D:\mohanad study\ERU Study\level 3\semester 2\Predictive Analytics\project\GoldExports\Gold_Fact_Orders_2026-05-08.csv")
Fact_Orders_Items = pd.read_csv("D:\mohanad study\ERU Study\level 3\semester 2\Predictive Analytics\project\GoldExports\Gold_Fact_Order_Items_2026-05-08.csv")
Fact_Marketing = pd.read_csv("D:\mohanad study\ERU Study\level 3\semester 2\Predictive Analytics\project\GoldExports\Gold_Fact_Marketing_Funnel_2026-05-08.csv")

In [158]:
Dim_Customers.head()

,customer_unique_id,zip_code,city,state,latitude,longitude,load_date_timestamp
0,0000366f3b9a7992bf8c76cfdf3221e2,7787,cajamar,SP,-23.340235,-46.830140,5/7/2026 11:19:13 PM
1,0000b849f77a49e4a4ce2b2a4ca5be3f,6053,osasco,SP,-23.559115,-46.787626,5/7/2026 11:19:13 PM
2,0000f46a3911fa3c0805444483337064,88115,sao jose,SC,-27.542880,-48.633426,5/7/2026 11:19:13 PM
3,0000f6ccb0745a6a4b88665a16c9f078,66812,belem,PA,-1.312214,-48.483159,5/7/2026 11:19:13 PM
4,0004aac84e0df4da2b147fca70cf8255,18040,sorocaba,SP,-23.505548,-47.469705,5/7/2026 11:19:13 PM

In [159]:
Dim_Date.head()

,date_key,full_date,year_number,quarter_number,month_number,month_name,day_name,is_weekend,load_date_timestamp
0,20150101,1/1/2015 12:00:00 AM,2015,1,1,January,Thursday,False,5/7/2026 11:19:11 PM
1,20150102,1/2/2015 12:00:00 AM,2015,1,1,January,Friday,False,5/7/2026 11:19:11 PM
2,20150103,1/3/2015 12:00:00 AM,2015,1,1,January,Saturday,True,5/7/2026 11:19:11 PM
3,20150104,1/4/2015 12:00:00 AM,2015,1,1,January,Sunday,True,5/7/2026 11:19:11 PM
4,20150105,1/5/2015 12:00:00 AM,2015,1,1,January,Monday,False,5/7/2026 11:19:11 PM

In [160]:
Dim_Products

,product_id,category_name_pt,category_name_en,name_length,description_length,photo_count,weight_g,length_cm,height_cm,width_cm,volume_cm3,load_date_timestamp
0,00066f42aeeb9f3007548bb9d3f33c38,perfumaria,perfumery,53.0,596.0,6.0,300.0,20.0,16.0,16.0,5120.0,5/7/2026 11:19:11 PM
1,00088930e925c41fd95ebfe695fd2655,automotivo,auto,56.0,752.0,4.0,1225.0,55.0,10.0,26.0,14300.0,5/7/2026 11:19:11 PM
2,0009406fd7479715e4bef61dd91f2462,cama mesa banho,bed bath table,50.0,266.0,2.0,300.0,45.0,15.0,35.0,23625.0,5/7/2026 11:19:11 PM
3,000b8f95fcb9e0096488278317764d19,utilidades domesticas,housewares,25.0,364.0,3.0,550.0,19.0,24.0,12.0,5472.0,5/7/2026 11:19:11 PM
4,000d9be29b5207b54e86aa1b1ac54872,relogios presentes,watches gifts,48.0,613.0,4.0,250.0,22.0,11.0,15.0,3630.0,5/7/2026 11:19:11 PM
...,...,...,...,...,...,...,...,...,...,...,...,...
32946,fff6177642830a9a94a0f2cba5e476d1,cool stuff,cool stuff,54.0,842.0,1.0,1400.0,42.0,25.0,15.0,15750.0,5/7/2026 11:19:11 PM
32947,fff81cc3158d2725c0655ab9ba0f712c,beleza saude,health beauty,54.0,643.0,1.0,58.0,16.0,16.0,11.0,2816.0,5/7/2026 11:19:11 PM
32948,fff9553ac224cec9d15d49f5a263411f,fashion bolsas e acessorios,fashion bags accessories,22.0,328.0,3.0,150.0,16.0,13.0,11.0,2288.0,5/7/2026 11:19:11 PM
32949,fffdb2d0ec8d6a61f0a0a0db3f25b441,informatica acessorios,computers accessories,47.0,501.0,5.0,150.0,16.0,4.0,13.0,832.0,5/7/2026 11:19:11 PM
32950,fffe9eeff12fcbd74a2f2b007dde0c58,brinquedos,toys,57.0,1536.0,3.0,3900.0,43.0,16.0,11.0,7568.0,5/7/2026 11:19:11 PM

In [161]:
Dim_Sellers

,seller_id,zip_code,city,state,latitude,longitude,business_segment,business_type,lead_type,behaviour_profile,catalog_size,declared_monthly_revenue,came_from_marketing,load_date_timestamp
0,0015a82c2db000af6aaaf3ae2ecb0532,9080,santo andre,SP,-23.640444,-46.541742,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM
1,001cca7ae9ae17fb1caed9dfb1094831,29156,cariacica,ES,-20.278513,-40.411675,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM
2,001e6ad469a905060d959994f1b41e4f,24754,sao goncalo,RJ,-22.872355,-43.027433,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM
3,002100f778ceb8431b7a1020ff7ab48f,14405,franca,SP,-20.528759,-47.411110,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM
4,003554e2dce176b5555353e4f3555ac8,74565,goiania,GO,-16.640574,-49.276483,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3090,ffcfefa19b08742c5d315f2791395ee5,80045,curitiba,PR,-25.425730,-49.253916,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM
3091,ffdd9f82b9a447f6f8d4b91554cc7dd3,80030,curitiba,PR,-25.417039,-49.260760,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM
3092,ffeee66ac5d5a62fe688b9d26f83f534,15130,mirassol,SP,-20.814772,-49.506928,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM
3093,fffd5413c0700ac820c7069d66d98c89,13908,amparo,SP,-22.721605,-46.844150,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM
3094,ffff564a4f9085cd26170f4732393726,13070,campinas,SP,-22.892058,-47.082443,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM

In [162]:
Fact_Orders

,order_id,customer_unique_id,purchase_date_key,order_status,total_payment,primary_payment_type,review_score,review_text,delivery_days_actual,is_late_delivery,is_invalid_payment,load_date_timestamp
0,00010242fe8c5a6d1ba2dd792cb16214,871766c5855e863f6eccc05f988b23cb,20170913,delivered,72.19,credit card,5.0,perfeito produto entregue antes do combinado,7.0,False,False,5/7/2026 11:19:17 PM
1,00018f77f2f0320c557190d7a144bdd3,eb28e67c4c0b83846050ddfb8a35d051,20170426,delivered,259.83,credit card,4.0,NaN,16.0,False,False,5/7/2026 11:19:17 PM
2,000229ec398224ef6ca0657da4fc703e,3818d81c6709e39d06b2738a8d3a2474,20180114,delivered,216.87,credit card,5.0,chegou antes do prazo previsto e o produto sur...,8.0,False,False,5/7/2026 11:19:17 PM
3,00024acbcdf0a6daa1e931b038114c75,af861d436cfc08b2c2ddefd0ba074622,20180808,delivered,25.78,credit card,4.0,NaN,6.0,False,False,5/7/2026 11:19:17 PM
4,00042b26cf59d7ce69dfabb4e55b4fd9,64b576fb70d441e8f1b2d7d446e483c5,20170204,delivered,218.04,credit card,5.0,gostei pois veio no prazo determinado,25.0,False,False,5/7/2026 11:19:17 PM
...,...,...,...,...,...,...,...,...,...,...,...,...
99436,fffc94f6ce00a00581880bf54a75a037,0c9aeda10a71f369396d0c04dce13a64,20180423,delivered,343.40,boleto,5.0,NaN,17.0,False,False,5/7/2026 11:19:17 PM
99437,fffcd46ef2263f404302a634eb57f7eb,0da9fe112eae0c74d3ba1fe16de0988b,20180714,delivered,386.53,boleto,5.0,NaN,9.0,False,False,5/7/2026 11:19:17 PM
99438,fffce4705a9662cd70adb13d4a31832d,cd79b407828f02fdbba457111c38e4c4,20171023,delivered,116.85,credit card,5.0,NaN,5.0,False,False,5/7/2026 11:19:17 PM
99439,fffe18544ffabc95dfada21779c9644f,eb803377c9315b564bdedad672039306,20170814,delivered,64.71,credit card,5.0,recebi o produto antes do prazo e corretamente,2.0,False,False,5/7/2026 11:19:17 PM
99440,fffe41c64501cc87c801fd61db3f6244,cd76a00d8e3ca5e6ab9ed9ecb6667ac4,20180609,delivered,55.79,credit card,NaN,NaN,5.0,False,False,5/7/2026 11:19:17 PM

In [163]:
Fact_Orders_Items

,order_item_key,order_id,product_id,seller_id,purchase_date_key,order_purchase_timestamp,order_delivered_customer_date,price,freight_value,total_item_value,load_date_timestamp
0,1,00010242fe8c5a6d1ba2dd792cb16214,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,20170913,9/13/2017 8:59:00 AM,9/20/2017 11:43:00 PM,58.90,13.29,72.19,5/7/2026 11:19:25 PM
1,2,00018f77f2f0320c557190d7a144bdd3,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,20170426,4/26/2017 10:53:00 AM,5/12/2017 4:04:00 PM,239.90,19.93,259.83,5/7/2026 11:19:25 PM
2,3,000229ec398224ef6ca0657da4fc703e,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,20180114,1/14/2018 2:33:00 PM,1/22/2018 1:19:00 PM,199.00,17.87,216.87,5/7/2026 11:19:25 PM
3,4,00024acbcdf0a6daa1e931b038114c75,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,20180808,8/8/2018 10:00:00 AM,8/14/2018 1:32:00 PM,12.99,12.79,25.78,5/7/2026 11:19:25 PM
4,5,00042b26cf59d7ce69dfabb4e55b4fd9,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,20170204,2/4/2017 1:57:00 PM,3/1/2017 4:42:00 PM,199.90,18.14,218.04,5/7/2026 11:19:25 PM
...,...,...,...,...,...,...,...,...,...,...,...
112645,112646,fffc94f6ce00a00581880bf54a75a037,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,20180423,4/23/2018 1:57:00 PM,5/10/2018 10:56:00 PM,299.99,43.41,343.40,5/7/2026 11:19:25 PM
112646,112647,fffcd46ef2263f404302a634eb57f7eb,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,20180714,7/14/2018 10:26:00 AM,7/23/2018 8:31:00 PM,350.00,36.53,386.53,5/7/2026 11:19:25 PM
112647,112648,fffce4705a9662cd70adb13d4a31832d,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,20171023,10/23/2017 5:07:00 PM,10/28/2017 12:22:00 PM,99.90,16.95,116.85,5/7/2026 11:19:25 PM
112648,112649,fffe18544ffabc95dfada21779c9644f,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,20170814,8/14/2017 11:02:00 PM,8/16/2017 9:59:00 PM,55.99,8.72,64.71,5/7/2026 11:19:25 PM
112649,112650,fffe41c64501cc87c801fd61db3f6244,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,20180609,6/9/2018 5:00:00 PM,6/14/2018 5:56:00 PM,43.00,12.79,55.79,5/7/2026 11:19:25 PM

In [164]:
Fact_Marketing

,mql_id,seller_id,first_contact_date_key,won_date_key,lead_origin,landing_page_id,sdr_id,sr_id,is_converted,days_to_close,load_date_timestamp
0,0002ac0d783338cfeab0b2bdbd872cda,NaN,20171114,NaN,unknown,b76ef37428e6799c421989521c0e5077,NaN,NaN,False,NaN,5/7/2026 11:19:29 PM
1,000dd3543ac84d906eae52e7c779bb2a,NaN,20180405,20180424.0,organic search,b48ec5f3b04e9068441002a19df93c6c,a8387c01a09e99ce014107505b92388c,9e4d1098a3b0f5da39b0bc48f9876645,True,19.0,5/7/2026 11:19:29 PM
2,001d3439223b7bb23ed89b9c8890d096,NaN,20180414,NaN,paid search,35c9b150ab36fe584c1f24fd458c453a,NaN,NaN,False,NaN,5/7/2026 11:19:29 PM
3,00275937100699204a3d5ae3caf7190d,NaN,20180111,NaN,organic search,a7982125ff7aa3b2054c6e44f9d28522,NaN,NaN,False,NaN,5/7/2026 11:19:29 PM
4,003d859bbd84a526b9e06340ce7d185f,NaN,20180402,NaN,direct traffic,22c29808c4f815213303f8933030604c,NaN,NaN,False,NaN,5/7/2026 11:19:29 PM
...,...,...,...,...,...,...,...,...,...,...,...
7995,ffe640179b554e295c167a2f6be528e0,ed8cb7b190ceb6067227478e48cf8dde,20171009,20180703.0,unknown,a0fbc0263cb98bdb0d72b9f9f283a172,4b339f9567d060bcea4f5136b9f5949e,d3d1e91a157ea7f90548eef82f1955e3,True,267.0,5/7/2026 11:19:29 PM
7996,ffec39090fa0c85692730fdbd647e34d,NaN,20180417,NaN,email,515742ea988a44a8ca0ddc44ff92735f,NaN,NaN,False,NaN,5/7/2026 11:19:29 PM
7997,ffec991bf0f35f7e7688cf0d39c9f9f4,NaN,20171123,NaN,unknown,b76ef37428e6799c421989521c0e5077,NaN,NaN,False,NaN,5/7/2026 11:19:29 PM
7998,fff8db9478d2fd72df65a67ee6b62f67,bdae679a9b282249bc23b9b69dae9a99,20180120,20180124.0,direct traffic,c0fa54bbdd331f215aa84b4dd86d7255,4b339f9567d060bcea4f5136b9f5949e,6565aa9ce3178a5caf6171827af3a9ba,True,4.0,5/7/2026 11:19:29 PM
7999,fffffe98d0963d27015c198262d97221,NaN,20180125,NaN,social,88740e65d5d6b056e0cda098e1ea6313,NaN,NaN,False,NaN,5/7/2026 11:19:29 PM

In [165]:
Fact_Marketing[Fact_Marketing["is_converted"] == True].count()

mql_id                    842
seller_id                 380
first_contact_date_key    842
won_date_key              842
lead_origin               828
landing_page_id           842
sdr_id                    842
sr_id                     842
is_converted              842
days_to_close             842
load_date_timestamp       842
dtype: int64

In [166]:
Fact_Marketing[(Fact_Marketing["won_date_key"].notnull()) & (Fact_Marketing["seller_id"].isnull())].count()

mql_id                    462
seller_id                   0
first_contact_date_key    462
won_date_key              462
lead_origin               452
landing_page_id           462
sdr_id                    462
sr_id                     462
is_converted              462
days_to_close             462
load_date_timestamp       462
dtype: int64

# Preprocessing

## Dim_Customers

In [167]:
Dim_Customers.head()

,customer_unique_id,zip_code,city,state,latitude,longitude,load_date_timestamp
0,0000366f3b9a7992bf8c76cfdf3221e2,7787,cajamar,SP,-23.340235,-46.830140,5/7/2026 11:19:13 PM
1,0000b849f77a49e4a4ce2b2a4ca5be3f,6053,osasco,SP,-23.559115,-46.787626,5/7/2026 11:19:13 PM
2,0000f46a3911fa3c0805444483337064,88115,sao jose,SC,-27.542880,-48.633426,5/7/2026 11:19:13 PM
3,0000f6ccb0745a6a4b88665a16c9f078,66812,belem,PA,-1.312214,-48.483159,5/7/2026 11:19:13 PM
4,0004aac84e0df4da2b147fca70cf8255,18040,sorocaba,SP,-23.505548,-47.469705,5/7/2026 11:19:13 PM

In [168]:
print("--- Data Info ---")
Dim_Customers.info()

print("\n--- Missing Values ---")
print(Dim_Customers.isnull().sum())

print("\n--- Duplicates ---")
print("Exact duplicates:", Dim_Customers.duplicated().sum())
print("Duplicate IDs:", Dim_Customers.duplicated(subset=['customer_unique_id']).sum())

# Descriptive statistics to detect any anomalies (e.g., out-of-bound coordinates)
Dim_Customers.describe()

--- Data Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96096 entries, 0 to 96095
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_unique_id   96096 non-null  object
 1   zip_code             96096 non-null  int64
 2   city                 96096 non-null  object
 3   state                96096 non-null  object
 4   latitude             95828 non-null  float64
 5   longitude            95828 non-null  float64
 6   load_date_timestamp  96096 non-null  object
dtypes: float64(2), int64(1), object(4)
memory usage: 5.1+ MB

--- Missing Values ---
customer_unique_id       0
zip_code                 0
city                     0
state                    0
latitude               268
longitude              268
load_date_timestamp      0
dtype: int64

--- Duplicates ---
Exact duplicates: 0
Duplicate IDs: 0

           zip_code      latitude     longitude
count  96096.000000  95828.000000  95828.000000
mean   35187.405449    -21.179272    -46.173025
std    29801.850077      5.622533      4.059785
min     1003.000000    -33.689948    -72.668881
25%    11390.000000    -23.589279    -48.107784
50%    24440.000000    -22.924015    -46.630906
75%    59044.500000    -20.129695    -43.597630
max    99990.000000     42.184003     -8.723762

In [169]:
# 1. Initial Cleaning (As done previously)
Dim_Customers['zip_code'] = Dim_Customers['zip_code'].astype(str).str.zfill(5)
Dim_Customers['load_date_timestamp'] = pd.to_datetime(Dim_Customers['load_date_timestamp'])
Dim_Customers['city'] = Dim_Customers['city'].str.lower().str.strip()
Dim_Customers['state'] = Dim_Customers['state'].str.upper().str.strip()

# Set anomalous coordinates (outside Brazil) to NaN
lat_min, lat_max = -33.75, 5.27
lon_min, lon_max = -73.98, -34.79
invalid_mask = (
    (Dim_Customers['latitude'] < lat_min) | (Dim_Customers['latitude'] > lat_max) |
    (Dim_Customers['longitude'] < lon_min) | (Dim_Customers['longitude'] > lon_max)
)
Dim_Customers.loc[invalid_mask, ['latitude', 'longitude']] = np.nan

# 2. Prepare Data for Multiple Imputation
# We need to encode categorical strings into numbers for the model
encoder = OrdinalEncoder()
df_for_imputation = Dim_Customers.copy()

# Encode City and State
df_for_imputation[['city_encoded', 'state_encoded']] = encoder.fit_transform(df_for_imputation[['city', 'state']])

# Convert zip_code to float as it's a strong geographic indicator
df_for_imputation['zip_code_num'] = df_for_imputation['zip_code'].astype(float)

# Select the features that will participate in the Imputation algorithm
features_to_impute = ['zip_code_num', 'state_encoded', 'city_encoded', 'latitude', 'longitude']
data_matrix = df_for_imputation[features_to_impute]

print("Data matrix successfully prepared for Multiple Imputation...")

Data matrix successfully prepared for Multiple Imputation...

In [170]:
# 3. Build and Run the Iterative Imputer (MICE)
# We use Random Forest for high accuracy (n_estimators=20 is used to balance speed and accuracy)
imputer = IterativeImputer(
    estimator=RandomForestRegressor(n_estimators=20, random_state=42),
    max_iter=10,        # Number of imputation iterations
    random_state=42,
    verbose=2           # To show progress during training
)

print("Running MICE Imputation (This may take a moment due to the size of the dataset)...")
# Apply the algorithm to fill the missing values
imputed_matrix = imputer.fit_transform(data_matrix)

# 4. Retrieve the imputed coordinates back into the original DataFrame
# Latitude and Longitude are at index 3 and 4 in the features_to_impute list
Dim_Customers['latitude'] = imputed_matrix[:, 3]
Dim_Customers['longitude'] = imputed_matrix[:, 4]

# Final check to ensure there are no missing values left
print("\nMissing values after Multiple Imputation:")
print(Dim_Customers.isnull().sum())

Running MICE Imputation (This may take a moment due to the size of the dataset)...
[IterativeImputer] Completing matrix with shape (96096, 5)
[IterativeImputer] Ending imputation round 1/10, elapsed time 15.59
[IterativeImputer] Change: 26.814604092110052, scaled tolerance: 99.99000000000001
[IterativeImputer] Early stopping criterion reached.

Missing values after Multiple Imputation:
customer_unique_id     0
zip_code               0
city                   0
state                  0
latitude               0
longitude              0
load_date_timestamp    0
dtype: int64

In [171]:
Dim_Customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96096 entries, 0 to 96095
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_unique_id   96096 non-null  object
 1   zip_code             96096 non-null  object
 2   city                 96096 non-null  object
 3   state                96096 non-null  object
 4   latitude             96096 non-null  float64
 5   longitude            96096 non-null  float64
 6   load_date_timestamp  96096 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(4)
memory usage: 5.1+ MB

## Dim_Products

In [172]:
# Display the first 5 rows to get an initial look
Dim_Products

,product_id,category_name_pt,category_name_en,name_length,description_length,photo_count,weight_g,length_cm,height_cm,width_cm,volume_cm3,load_date_timestamp
0,00066f42aeeb9f3007548bb9d3f33c38,perfumaria,perfumery,53.0,596.0,6.0,300.0,20.0,16.0,16.0,5120.0,5/7/2026 11:19:11 PM
1,00088930e925c41fd95ebfe695fd2655,automotivo,auto,56.0,752.0,4.0,1225.0,55.0,10.0,26.0,14300.0,5/7/2026 11:19:11 PM
2,0009406fd7479715e4bef61dd91f2462,cama mesa banho,bed bath table,50.0,266.0,2.0,300.0,45.0,15.0,35.0,23625.0,5/7/2026 11:19:11 PM
3,000b8f95fcb9e0096488278317764d19,utilidades domesticas,housewares,25.0,364.0,3.0,550.0,19.0,24.0,12.0,5472.0,5/7/2026 11:19:11 PM
4,000d9be29b5207b54e86aa1b1ac54872,relogios presentes,watches gifts,48.0,613.0,4.0,250.0,22.0,11.0,15.0,3630.0,5/7/2026 11:19:11 PM
...,...,...,...,...,...,...,...,...,...,...,...,...
32946,fff6177642830a9a94a0f2cba5e476d1,cool stuff,cool stuff,54.0,842.0,1.0,1400.0,42.0,25.0,15.0,15750.0,5/7/2026 11:19:11 PM
32947,fff81cc3158d2725c0655ab9ba0f712c,beleza saude,health beauty,54.0,643.0,1.0,58.0,16.0,16.0,11.0,2816.0,5/7/2026 11:19:11 PM
32948,fff9553ac224cec9d15d49f5a263411f,fashion bolsas e acessorios,fashion bags accessories,22.0,328.0,3.0,150.0,16.0,13.0,11.0,2288.0,5/7/2026 11:19:11 PM
32949,fffdb2d0ec8d6a61f0a0a0db3f25b441,informatica acessorios,computers accessories,47.0,501.0,5.0,150.0,16.0,4.0,13.0,832.0,5/7/2026 11:19:11 PM
32950,fffe9eeff12fcbd74a2f2b007dde0c58,brinquedos,toys,57.0,1536.0,3.0,3900.0,43.0,16.0,11.0,7568.0,5/7/2026 11:19:11 PM

In [173]:
print("--- Data Info ---")
Dim_Products.info()

print("\n--- Missing Values ---")
print(Dim_Products.isnull().sum())

print("\n--- Impossible Physical Values ---")
print("Products with 0g weight:", (Dim_Products['weight_g'] == 0).sum())

# Let's check why there are more missing English categories than Portuguese ones
missing_en_but_has_pt = Dim_Products[Dim_Products['category_name_pt'].notnull() & Dim_Products['category_name_en'].isnull()]
print("\n--- Categories missing English translation ---")
print(missing_en_but_has_pt['category_name_pt'].unique())

--- Data Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           32951 non-null  object
 1   category_name_pt     32341 non-null  object
 2   category_name_en     32328 non-null  object
 3   name_length          32341 non-null  float64
 4   description_length   32341 non-null  float64
 5   photo_count          32341 non-null  float64
 6   weight_g             32949 non-null  float64
 7   length_cm            32949 non-null  float64
 8   height_cm            32949 non-null  float64
 9   width_cm             32949 non-null  float64
 10  volume_cm3           32949 non-null  float64
 11  load_date_timestamp  32951 non-null  object
dtypes: float64(8), object(4)
memory usage: 3.0+ MB

--- Missing Values ---
product_id               0
category_name_pt       610
category_name_en       623
name_length            610
description_length     610
photo_count            610
weight_g                 2
length_cm                2
height_cm                2
width_cm                 2
volume_cm3               2
load_date_timestamp      0
dtype: int64

--- Impossible Physical Values ---
Products with 0g weight: 4

--- Categories missing English translation ---
['pc gamer' 'portateis cozinha e preparadores de alimentos']

In [174]:
# 1. Fix Categorical Text Issues First
# Map known missing English translations
cat_mapping = {
    'pc gamer': 'pc gamer',
    'portateis cozinha e preparadores de alimentos': 'kitchen portables'
}
mask = Dim_Products['category_name_pt'].notnull() & Dim_Products['category_name_en'].isnull()
Dim_Products.loc[mask, 'category_name_en'] = Dim_Products.loc[mask, 'category_name_pt'].map(cat_mapping)

# Fill completely missing categories with 'unknown' so the model can group them together
Dim_Products['category_name_pt'] = Dim_Products['category_name_pt'].fillna('desconhecido')
Dim_Products['category_name_en'] = Dim_Products['category_name_en'].fillna('unknown')

# Fix impossible physical weights (0g) by turning them into NaN
Dim_Products['weight_g'] = Dim_Products['weight_g'].replace(0, np.nan)

# Format Date
Dim_Products['load_date_timestamp'] = pd.to_datetime(Dim_Products['load_date_timestamp'])

# 2. Prepare Data for KNN (Encoding & Feature Selection)
encoder = OrdinalEncoder()
df_knn = Dim_Products.copy()

# Encode the text categories
df_knn[['cat_pt_encoded', 'cat_en_encoded']] = encoder.fit_transform(df_knn[['category_name_pt', 'category_name_en']])

# Define the numerical matrix we want to impute
features_to_impute = [
    'cat_pt_encoded', 'cat_en_encoded', 
    'name_length', 'description_length', 'photo_count',
    'weight_g', 'length_cm', 'height_cm', 'width_cm'
]
data_matrix = df_knn[features_to_impute]

# 3. Feature Scaling (CRITICAL for KNN)
scaler = MinMaxScaler()
scaled_matrix = scaler.fit_transform(data_matrix)

print("Product data encoded and scaled. Ready for KNN Imputation...")

Product data encoded and scaled. Ready for KNN Imputation...

In [175]:
# 4. Build and Run the KNN Imputer
knn_imputer = KNNImputer(n_neighbors=5, weights='distance')

print("Running KNN Imputation for Products...")
imputed_scaled_matrix = knn_imputer.fit_transform(scaled_matrix)

# 5. Inverse Transform (Un-scale back to real-world values)
imputed_matrix = scaler.inverse_transform(imputed_scaled_matrix)

# 6. Retrieve the imputed numerical columns back into the DataFrame
# The columns start from index 2 in our 'features_to_impute' list
cols_to_restore = ['name_length', 'description_length', 'photo_count', 'weight_g', 'length_cm', 'height_cm', 'width_cm']

for i, col in enumerate(cols_to_restore):
    Dim_Products[col] = imputed_matrix[:, i+2]  # +2 skips the encoded category columns

# 7. Post-Processing: Round discrete values to whole numbers
Dim_Products['name_length'] = Dim_Products['name_length'].round()
Dim_Products['description_length'] = Dim_Products['description_length'].round()
Dim_Products['photo_count'] = Dim_Products['photo_count'].round()

# 8. Recalculate Volume using the newly imputed & accurate dimensions
Dim_Products['volume_cm3'] = Dim_Products['length_cm'] * Dim_Products['height_cm'] * Dim_Products['width_cm']

# Final Check
print("\nMissing values after KNN Imputation:")
print(Dim_Products.isnull().sum())
print("\nProducts with 0g weight:", (Dim_Products['weight_g'] == 0).sum())

Running KNN Imputation for Products...

Missing values after KNN Imputation:
product_id             0
category_name_pt       0
category_name_en       0
name_length            0
description_length     0
photo_count            0
weight_g               0
length_cm              0
height_cm              0
width_cm               0
volume_cm3             0
load_date_timestamp    0
dtype: int64

Products with 0g weight: 0

## Dim_Sellers

In [176]:
Dim_Sellers

,seller_id,zip_code,city,state,latitude,longitude,business_segment,business_type,lead_type,behaviour_profile,catalog_size,declared_monthly_revenue,came_from_marketing,load_date_timestamp
0,0015a82c2db000af6aaaf3ae2ecb0532,9080,santo andre,SP,-23.640444,-46.541742,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM
1,001cca7ae9ae17fb1caed9dfb1094831,29156,cariacica,ES,-20.278513,-40.411675,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM
2,001e6ad469a905060d959994f1b41e4f,24754,sao goncalo,RJ,-22.872355,-43.027433,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM
3,002100f778ceb8431b7a1020ff7ab48f,14405,franca,SP,-20.528759,-47.411110,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM
4,003554e2dce176b5555353e4f3555ac8,74565,goiania,GO,-16.640574,-49.276483,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3090,ffcfefa19b08742c5d315f2791395ee5,80045,curitiba,PR,-25.425730,-49.253916,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM
3091,ffdd9f82b9a447f6f8d4b91554cc7dd3,80030,curitiba,PR,-25.417039,-49.260760,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM
3092,ffeee66ac5d5a62fe688b9d26f83f534,15130,mirassol,SP,-20.814772,-49.506928,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM
3093,fffd5413c0700ac820c7069d66d98c89,13908,amparo,SP,-22.721605,-46.844150,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM
3094,ffff564a4f9085cd26170f4732393726,13070,campinas,SP,-22.892058,-47.082443,NaN,NaN,NaN,NaN,NaN,NaN,False,5/7/2026 11:19:16 PM

In [177]:
# Display initial information
print("--- Initial Sellers Info ---")
Dim_Sellers.info()
print("\n--- Missing Values ---")
print(Dim_Sellers.isnull().sum())

--- Initial Sellers Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   seller_id                 3095 non-null   object
 1   zip_code                  3095 non-null   int64
 2   city                      3093 non-null   object
 3   state                     3095 non-null   object
 4   latitude                  3053 non-null   float64
 5   longitude                 3053 non-null   float64
 6   business_segment          380 non-null    object
 7   business_type             377 non-null    object
 8   lead_type                 377 non-null    object
 9   behaviour_profile         289 non-null    object
 10  catalog_size              0 non-null      float64
 11  declared_monthly_revenue  380 non-null    float64
 12  came_from_marketing       3095 non-null   bool
 13  load_date_timestamp       3095 non-null   object
dtypes: bool(1), float64(4), int64(1), object(8)
memory usage: 317.5+ KB

--- Missing Values ---
seller_id                      0
zip_code                       0
city                           2
state                          0
latitude                      42
longitude                     42
business_segment            2715
business_type               2718
lead_type                   2718
behaviour_profile           2806
catalog_size                3095
declared_monthly_revenue    2715
came_from_marketing            0
load_date_timestamp            0
dtype: int64

In [178]:
# 1. Fix Zip Codes (Pad with leading zeros to ensure 5 digits)
Dim_Sellers['zip_code'] = Dim_Sellers['zip_code'].astype(str).str.zfill(5)

# 2. Handle missing text/categorical data (Without dropping any columns)
# Fill missing cities with 'unknown'
Dim_Sellers['city'] = Dim_Sellers['city'].fillna('unknown').str.lower().str.strip()
Dim_Sellers['state'] = Dim_Sellers['state'].str.upper().str.strip()

# Fill missing marketing columns with 'unknown' as requested
marketing_cols = ['business_segment', 'business_type', 'lead_type', 'behaviour_profile']
for col in marketing_cols:
    Dim_Sellers[col] = Dim_Sellers[col].fillna('unknown').str.lower().str.strip()

# 3. Format the timestamp
Dim_Sellers['load_date_timestamp'] = pd.to_datetime(Dim_Sellers['load_date_timestamp'])

# 4. Handle out-of-bounds coordinates (outside Brazil) by setting them to NaN for Imputation
lat_min, lat_max = -33.75, 5.27
lon_min, lon_max = -73.98, -34.79

invalid_mask = (
    (Dim_Sellers['latitude'] < lat_min) | (Dim_Sellers['latitude'] > lat_max) |
    (Dim_Sellers['longitude'] < lon_min) | (Dim_Sellers['longitude'] > lon_max)
)
Dim_Sellers.loc[invalid_mask, ['latitude', 'longitude']] = np.nan

print("Initial preprocessing complete. Total columns maintained:", len(Dim_Sellers.columns))

Initial preprocessing complete. Total columns maintained: 14

In [179]:
# 1. Prepare Data and encode text so the KNN model can process it
encoder = OrdinalEncoder()
df_knn = Dim_Sellers.copy()

# Encode City and State into numbers
df_knn[['city_encoded', 'state_encoded']] = encoder.fit_transform(df_knn[['city', 'state']])
df_knn['zip_code_num'] = df_knn['zip_code'].astype(float)

# Select the features that will participate in the KNN study
features_to_impute = ['state_encoded', 'city_encoded', 'zip_code_num', 'latitude', 'longitude']
data_matrix = df_knn[features_to_impute]

# 2. Feature Scaling (Crucial for KNN to balance calculations)
scaler = MinMaxScaler()
scaled_matrix = scaler.fit_transform(data_matrix)

# 3. Build and Run the KNN Imputer
print("Running KNN Imputation to estimate missing coordinates...")
knn_imputer = KNNImputer(n_neighbors=5, weights='distance')
imputed_scaled_matrix = knn_imputer.fit_transform(scaled_matrix)

# 4. Inverse Transform (Un-scale back to real GPS coordinates)
imputed_matrix = scaler.inverse_transform(imputed_scaled_matrix)

# 5. Retrieve the newly imputed coordinates back into the original DataFrame
# Latitude and Longitude are at index 3 and 4 in our features_to_impute list
Dim_Sellers['latitude'] = imputed_matrix[:, 3]
Dim_Sellers['longitude'] = imputed_matrix[:, 4]

# Display the result to verify no missing values remain in the processed columns
print("\nMissing values in processed columns after Imputation:")
print(Dim_Sellers[['city', 'state', 'latitude', 'longitude', 'business_segment']].isnull().sum())

Running KNN Imputation to estimate missing coordinates...

Missing values in processed columns after Imputation:
city                0
state               0
latitude            0
longitude           0
business_segment    0
dtype: int64

In [180]:
Dim_Sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   seller_id                 3095 non-null   object
 1   zip_code                  3095 non-null   object
 2   city                      3095 non-null   object
 3   state                     3095 non-null   object
 4   latitude                  3095 non-null   float64
 5   longitude                 3095 non-null   float64
 6   business_segment          3095 non-null   object
 7   business_type             3095 non-null   object
 8   lead_type                 3095 non-null   object
 9   behaviour_profile         3095 non-null   object
 10  catalog_size              0 non-null      float64
 11  declared_monthly_revenue  380 non-null    float64
 12  came_from_marketing       3095 non-null   bool
 13  load_date_timestamp       3095 non-null   datetime64[ns]
dtypes: bool(1), datetime64[ns](1), float64(4), object(8)
memory usage: 317.5+ KB

## Fact_Orders & Fact_Orders_Items

### Fact_Orders

In [181]:
Fact_Orders

,order_id,customer_unique_id,purchase_date_key,order_status,total_payment,primary_payment_type,review_score,review_text,delivery_days_actual,is_late_delivery,is_invalid_payment,load_date_timestamp
0,00010242fe8c5a6d1ba2dd792cb16214,871766c5855e863f6eccc05f988b23cb,20170913,delivered,72.19,credit card,5.0,perfeito produto entregue antes do combinado,7.0,False,False,5/7/2026 11:19:17 PM
1,00018f77f2f0320c557190d7a144bdd3,eb28e67c4c0b83846050ddfb8a35d051,20170426,delivered,259.83,credit card,4.0,NaN,16.0,False,False,5/7/2026 11:19:17 PM
2,000229ec398224ef6ca0657da4fc703e,3818d81c6709e39d06b2738a8d3a2474,20180114,delivered,216.87,credit card,5.0,chegou antes do prazo previsto e o produto sur...,8.0,False,False,5/7/2026 11:19:17 PM
3,00024acbcdf0a6daa1e931b038114c75,af861d436cfc08b2c2ddefd0ba074622,20180808,delivered,25.78,credit card,4.0,NaN,6.0,False,False,5/7/2026 11:19:17 PM
4,00042b26cf59d7ce69dfabb4e55b4fd9,64b576fb70d441e8f1b2d7d446e483c5,20170204,delivered,218.04,credit card,5.0,gostei pois veio no prazo determinado,25.0,False,False,5/7/2026 11:19:17 PM
...,...,...,...,...,...,...,...,...,...,...,...,...
99436,fffc94f6ce00a00581880bf54a75a037,0c9aeda10a71f369396d0c04dce13a64,20180423,delivered,343.40,boleto,5.0,NaN,17.0,False,False,5/7/2026 11:19:17 PM
99437,fffcd46ef2263f404302a634eb57f7eb,0da9fe112eae0c74d3ba1fe16de0988b,20180714,delivered,386.53,boleto,5.0,NaN,9.0,False,False,5/7/2026 11:19:17 PM
99438,fffce4705a9662cd70adb13d4a31832d,cd79b407828f02fdbba457111c38e4c4,20171023,delivered,116.85,credit card,5.0,NaN,5.0,False,False,5/7/2026 11:19:17 PM
99439,fffe18544ffabc95dfada21779c9644f,eb803377c9315b564bdedad672039306,20170814,delivered,64.71,credit card,5.0,recebi o produto antes do prazo e corretamente,2.0,False,False,5/7/2026 11:19:17 PM
99440,fffe41c64501cc87c801fd61db3f6244,cd76a00d8e3ca5e6ab9ed9ecb6667ac4,20180609,delivered,55.79,credit card,NaN,NaN,5.0,False,False,5/7/2026 11:19:17 PM

In [182]:
Fact_Orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              99441 non-null  object
 1   customer_unique_id    99441 non-null  object
 2   purchase_date_key     99441 non-null  int64
 3   order_status          99441 non-null  object
 4   total_payment         99440 non-null  float64
 5   primary_payment_type  99440 non-null  object
 6   review_score          65049 non-null  float64
 7   review_text           26815 non-null  object
 8   delivery_days_actual  96476 non-null  float64
 9   is_late_delivery      96476 non-null  object
 10  is_invalid_payment    99441 non-null  bool
 11  load_date_timestamp   99441 non-null  object
dtypes: bool(1), float64(3), int64(1), object(7)
memory usage: 8.4+ MB

In [183]:
Fact_Orders['total_payment'].unique()

array([ 72.19, 259.83, 216.87, ..., 273.92, 343.4 , 386.53],
      shape=(27541,))

In [184]:
print("--- Orders Table Info ---")
print(f"Shape: {Fact_Orders.shape}")
print(Fact_Orders.isnull().sum())

--- Orders Table Info ---
Shape: (99441, 12)
order_id                    0
customer_unique_id          0
purchase_date_key           0
order_status                0
total_payment               1
primary_payment_type        1
review_score            34392
review_text             72626
delivery_days_actual     2965
is_late_delivery         2965
is_invalid_payment          0
load_date_timestamp         0
dtype: int64

### Fact_Orders_Items

In [185]:
Fact_Orders_Items

,order_item_key,order_id,product_id,seller_id,purchase_date_key,order_purchase_timestamp,order_delivered_customer_date,price,freight_value,total_item_value,load_date_timestamp
0,1,00010242fe8c5a6d1ba2dd792cb16214,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,20170913,9/13/2017 8:59:00 AM,9/20/2017 11:43:00 PM,58.90,13.29,72.19,5/7/2026 11:19:25 PM
1,2,00018f77f2f0320c557190d7a144bdd3,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,20170426,4/26/2017 10:53:00 AM,5/12/2017 4:04:00 PM,239.90,19.93,259.83,5/7/2026 11:19:25 PM
2,3,000229ec398224ef6ca0657da4fc703e,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,20180114,1/14/2018 2:33:00 PM,1/22/2018 1:19:00 PM,199.00,17.87,216.87,5/7/2026 11:19:25 PM
3,4,00024acbcdf0a6daa1e931b038114c75,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,20180808,8/8/2018 10:00:00 AM,8/14/2018 1:32:00 PM,12.99,12.79,25.78,5/7/2026 11:19:25 PM
4,5,00042b26cf59d7ce69dfabb4e55b4fd9,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,20170204,2/4/2017 1:57:00 PM,3/1/2017 4:42:00 PM,199.90,18.14,218.04,5/7/2026 11:19:25 PM
...,...,...,...,...,...,...,...,...,...,...,...
112645,112646,fffc94f6ce00a00581880bf54a75a037,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,20180423,4/23/2018 1:57:00 PM,5/10/2018 10:56:00 PM,299.99,43.41,343.40,5/7/2026 11:19:25 PM
112646,112647,fffcd46ef2263f404302a634eb57f7eb,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,20180714,7/14/2018 10:26:00 AM,7/23/2018 8:31:00 PM,350.00,36.53,386.53,5/7/2026 11:19:25 PM
112647,112648,fffce4705a9662cd70adb13d4a31832d,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,20171023,10/23/2017 5:07:00 PM,10/28/2017 12:22:00 PM,99.90,16.95,116.85,5/7/2026 11:19:25 PM
112648,112649,fffe18544ffabc95dfada21779c9644f,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,20170814,8/14/2017 11:02:00 PM,8/16/2017 9:59:00 PM,55.99,8.72,64.71,5/7/2026 11:19:25 PM
112649,112650,fffe41c64501cc87c801fd61db3f6244,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,20180609,6/9/2018 5:00:00 PM,6/14/2018 5:56:00 PM,43.00,12.79,55.79,5/7/2026 11:19:25 PM

In [186]:
print("\n--- Order Items Table Info ---")
print(f"Shape: {Fact_Orders_Items.shape}")
print(Fact_Orders_Items.isnull().sum())

--- Order Items Table Info ---
Shape: (112650, 11)
order_item_key                      0
order_id                            0
product_id                          0
seller_id                           0
purchase_date_key                   0
order_purchase_timestamp            0
order_delivered_customer_date    2454
price                               0
freight_value                       0
total_item_value                    0
load_date_timestamp                 0
dtype: int64

In [187]:
Q1  = Fact_Orders_Items['price'].quantile(0.25)
Q3  = Fact_Orders_Items['price'].quantile(0.75)
IQR = Q3 - Q1
Fact_Orders_Items['is_price_outlier'] = (
    (Fact_Orders_Items['price'] < Q1 - 1.5 * IQR) |
    (Fact_Orders_Items['price'] > Q3 + 1.5 * IQR)
)

In [188]:
Fact_Orders_Items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 12 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_item_key                 112650 non-null  int64
 1   order_id                       112650 non-null  object
 2   product_id                     112650 non-null  object
 3   seller_id                      112650 non-null  object
 4   purchase_date_key              112650 non-null  int64
 5   order_purchase_timestamp       112650 non-null  object
 6   order_delivered_customer_date  110196 non-null  object
 7   price                          112650 non-null  float64
 8   freight_value                  112650 non-null  float64
 9   total_item_value               112650 non-null  float64
 10  load_date_timestamp            112650 non-null  object
 11  is_price_outlier               112650 non-null  bool
dtypes: bool(1), float64(3), int64(2), object(6)
memory usage: 9.6+ MB

## Fact_Marketing

In [189]:
Fact_Marketing

,mql_id,seller_id,first_contact_date_key,won_date_key,lead_origin,landing_page_id,sdr_id,sr_id,is_converted,days_to_close,load_date_timestamp
0,0002ac0d783338cfeab0b2bdbd872cda,NaN,20171114,NaN,unknown,b76ef37428e6799c421989521c0e5077,NaN,NaN,False,NaN,5/7/2026 11:19:29 PM
1,000dd3543ac84d906eae52e7c779bb2a,NaN,20180405,20180424.0,organic search,b48ec5f3b04e9068441002a19df93c6c,a8387c01a09e99ce014107505b92388c,9e4d1098a3b0f5da39b0bc48f9876645,True,19.0,5/7/2026 11:19:29 PM
2,001d3439223b7bb23ed89b9c8890d096,NaN,20180414,NaN,paid search,35c9b150ab36fe584c1f24fd458c453a,NaN,NaN,False,NaN,5/7/2026 11:19:29 PM
3,00275937100699204a3d5ae3caf7190d,NaN,20180111,NaN,organic search,a7982125ff7aa3b2054c6e44f9d28522,NaN,NaN,False,NaN,5/7/2026 11:19:29 PM
4,003d859bbd84a526b9e06340ce7d185f,NaN,20180402,NaN,direct traffic,22c29808c4f815213303f8933030604c,NaN,NaN,False,NaN,5/7/2026 11:19:29 PM
...,...,...,...,...,...,...,...,...,...,...,...
7995,ffe640179b554e295c167a2f6be528e0,ed8cb7b190ceb6067227478e48cf8dde,20171009,20180703.0,unknown,a0fbc0263cb98bdb0d72b9f9f283a172,4b339f9567d060bcea4f5136b9f5949e,d3d1e91a157ea7f90548eef82f1955e3,True,267.0,5/7/2026 11:19:29 PM
7996,ffec39090fa0c85692730fdbd647e34d,NaN,20180417,NaN,email,515742ea988a44a8ca0ddc44ff92735f,NaN,NaN,False,NaN,5/7/2026 11:19:29 PM
7997,ffec991bf0f35f7e7688cf0d39c9f9f4,NaN,20171123,NaN,unknown,b76ef37428e6799c421989521c0e5077,NaN,NaN,False,NaN,5/7/2026 11:19:29 PM
7998,fff8db9478d2fd72df65a67ee6b62f67,bdae679a9b282249bc23b9b69dae9a99,20180120,20180124.0,direct traffic,c0fa54bbdd331f215aa84b4dd86d7255,4b339f9567d060bcea4f5136b9f5949e,6565aa9ce3178a5caf6171827af3a9ba,True,4.0,5/7/2026 11:19:29 PM
7999,fffffe98d0963d27015c198262d97221,NaN,20180125,NaN,social,88740e65d5d6b056e0cda098e1ea6313,NaN,NaN,False,NaN,5/7/2026 11:19:29 PM

In [190]:
print("--- Initial Marketing Info ---")
Fact_Marketing.info()
print("\n--- Missing Values ---")
print(Fact_Marketing.isnull().sum())

--- Initial Marketing Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   mql_id                  8000 non-null   object
 1   seller_id               380 non-null    object
 2   first_contact_date_key  8000 non-null   int64
 3   won_date_key            842 non-null    float64
 4   lead_origin             7940 non-null   object
 5   landing_page_id         8000 non-null   object
 6   sdr_id                  842 non-null    object
 7   sr_id                   842 non-null    object
 8   is_converted            8000 non-null   bool
 9   days_to_close           842 non-null    float64
 10  load_date_timestamp     8000 non-null   object
dtypes: bool(1), float64(2), int64(1), object(7)
memory usage: 632.9+ KB

--- Missing Values ---
mql_id                       0
seller_id                 7620
first_contact_date_key       0
won_date_key              7158
lead_origin                 60
landing_page_id              0
sdr_id                    7158
sr_id                     7158
is_converted                 0
days_to_close             7158
load_date_timestamp          0
dtype: int64